### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by jpita** [NoriSte/cypress-wait-until#104]
Hello,

I have [this problem](https://stackoverflow.com/questions/60431148/cypress-do-action-until-element-shows-on-screen) I'm trying to solve.

Gleb recommended cypress-wait-until but from the documentation I don't understand how to do it.

You mention a `checkFunction` that is supposed to be retried but I don't see it anywhere in the code, so I don't know where to put the code that is supposed to be retried.

**Comment by NoriSte** [comment]
Check the last [issue opened](https://github.com/NoriSte/cypress-wait-until/issues/75) and the explanation.

Then:
- **you** define the `checkFunction`
- in your case the solution will be something like
```js
cy.waitUntil(() => cy.flipPage().then(() => Cypress.$("#elementToBeChecked").length))
cy.get("#elementToBeChecked").should("exist")
```
(where the `checkFunction` is everything passed to `cy.waitUntil`)

Hope it helps! 😊

**Comment by jpita** [comment]
it works! thanks!
