### ISSUE TITLE
waitUntil with cy.visit()

### ISSUE THREAD

**Issue by Jacek-fstack** [NoriSte/cypress-wait-until#107]
Hello!
I saw one of your explanations here:
https://stackoverflow.com/questions/60431148/cypress-do-action-until-element-shows-on-screen/60446878#60446878

But is it possible at all to implement it for this case?
https://stackoverflow.com/questions/60503761/option-to-retry-command-in-cypress-after-it-failed

to use the waitUntil, I'd have to have an exposed jQuery for the cy.visit and I don't think it exists as it is?
Is it possible to add the functionality to your repo?
The issue is the visit() has an assertion in itself on the 'load' event and I can't do it without test failing.

Thank you!

**Comment by NoriSte** [comment]
Are you running the latest version of Cypress?
Anyway: unfortunately my waitUntil plugin can't be useful in this case because there is no "manual" alternatives to the `cy.visit` command 😕

**Comment by Jacek-fstack** [comment]
Thank you for the reply!
