### ISSUE TITLE
Cannot use this with webpack preprocessor

### ISSUE THREAD

**Issue by jbalasingham** [NoriSte/cypress-wait-until#114]
I followed the Typescript instructions from https://www.npmjs.com/package/cypress-wait-until#typescript and also added the import to the support command file. However, my project renders Typescript on the fly using https://github.com/cypress-io/cypress-webpack-preprocessor.
While coding, the **cy.waitUntil** command is visible via intellisense. However, when I run it, I get the following error.

> TypeError: cy.waitUntil is not a function

It doesn't matter which command I use. Even simple 
`cy.waitUntil(() => true);`
throws error.
This happens on both UI and Command Line.

Do you have a suggestion on how I can fix this? Please advise.

**Comment by NoriSte** [comment]
Hi Janahan, could you provide me a minimal repository that reproduces the problem to play with? Do you import other plugins that work out mine is the only one?
Thanks
Stefano

**Comment by NoriSte** [comment]
More: since you compile Typescript on the fly, are you sure that webpack compiling configuration is set up to correctly include waitUntil types?

**Comment by jbalasingham** [comment]
> More: since you compile Typescript on the fly, are you sure that webpack compiling configuration is set up to correctly include waitUntil types?
That's what I'm unsure of. I can't find an example of the types being configured on the webpack and based on what I can tell, it is supposed to use the types from the tsconfig.
Let me see if I can create a demo example of the issue. That way you can investigate on the matter.

**Comment by jbalasingham** [comment]
@NoriSte I have invited you to the sample repo I created. Master branch is the demo one and the waitUntil branch is with this plugin code implementation. So you can see the code change.

**Comment by NoriSte** [comment]
The problem is not with the plugin but with the TypeScript configuration. I tried with `cypress-pipe` too but the problem is the same. It's strange because the config seems correct, the VS Code' TS server finds the types correctly (since it suggest you booth `waitUntil` and `pipe` with the autocomplete). I made some tries but I have not managed to get it working, please let me know once you find a solution 🤔

**Comment by NoriSte** [comment]
@jbalasingham have you worked it out?

**Comment by jbalasingham** [comment]
@NoriSte Yeah. Sorry I didn't update. Been busy with some work. The issue was caused by the index file used in support was **.ts** and not **.js**. Renaming it fixed the dependency and plugin worked.

**Comment by NoriSte** [comment]
Good to know!! Thanks for sharing 😊

**Comment by NoriSte** [comment]
Meanwhile... Cypress [supports now TypeScript out of the box](https://github.com/cypress-io/cypress/releases/tag/v4.4.0) 😊

**Comment by jbalasingham** [comment]
:D Finally they come onboard.
