### ISSUE TITLE
Wait without timeout

### ISSUE THREAD

**Issue by Eduardo-Carneiro-CM** [NoriSte/cypress-wait-until#131]
Hello, I'm trying to use the plugin to wait for something that might not happen, is there a way I could like wait 5 seconds and if nothing happens test keeps running without failing?

**Comment by NoriSte** [comment]
Hi @Eduardo-Carneiro-CM! Since I have been asked twice in the last few days about it, I've added a [dedicated question in the documentation](https://github.com/NoriSte/cypress-wait-until#could-cywaituntil-avoid-failing-the-test), please take a look 😊

**Comment by Eduardo-Carneiro-CM** [comment]
Thank you
