### ISSUE TITLE
Wait for element change

### ISSUE THREAD

**Issue by Wulfheart** [NoriSte/cypress-wait-until#136]
Hello,

the functionality of this package is awesome. However I'm stuck on a little problem.
I have the following markup given:
````html
<div>
    <ul id="list" data-cy="some-timestamp">
        <li>Some item</li>
    </ul>
</div>
````
How can I detect a status change in the `<ul>` element assuming that the content which will appear is unknown?

Thank you in advance.

Edit: As I'm using server-side rendered partials I could fetch a timestamp together with the `ul` element and compare if the two timestamps are different. I'm not sure how this can be achieved as there is some storing of a variable involved. I'm not that proficient with async js. Any thoughts on this?

**Comment by NoriSte** [comment]
Hi @Wulfheart 

> How can I detect a status change in the <ul> element 

What do you mean by "status change"? A change in the children? A change in the attributes?

Is there anything that allows you to be completely sure that something changed? I guess that you have SSR and re-hydration in browserland? Timestamps could be a good idea.

Anyway: before speaking about how to use `cy.waitUntil` to detect a change we need to clarify how to detect a change at all, that's why I'm asking above 😉

**Comment by Wulfheart** [comment]
@NoriSte thanks for your quick response. Generally speaking I’d like to detect a DOM change in a specific container.

**Comment by NoriSte** [comment]
Tomorrow I could add a more complete answer, meanwhile take a look at [MutationObserver](https://developer.mozilla.org/it/docs/Web/API/MutationObserver).

**Comment by NoriSte** [comment]
Here's the solution, you can find it [this repository](https://github.com/NoriSte/cypress-detect-dom-changes) of mine. You do not need to use `cy.waitUntil` but I've added two tests, one with Cypress' built-in utilities and one with `cy.waitUntil`.

**Common part**:
```js
let mutationsHistory
beforeEach(() => {
  cy.visit('/')

  mutationsHistory = []
  cy.get('#some-id').then(($targetNode) => {
    const observer = new MutationObserver((mutationsList) => mutationsHistory.push(mutationsList))
    observer.observe($targetNode[0], { childList: true })
  })
})
```
leveraging the [MutationObserver API](https://developer.mozilla.org/it/docs/Web/API/MutationObserver), Cypress records all the mutations in the `mutationsList` array.

**Cypress built-in solution**
This simple script waits until the mutations array contains something
```js
cy.wrap(mutationsHistory)
  .should('have.length.greaterThan', 0)
```

**With cy.waitUntil**:
The same of the above code but with cy.waitUntil
```js
cy.waitUntil(() => mutationsHistory.length)
```

Always opt for the built-in solution if you can 😉

This is the full code of the test
```js
/// <reference types="Cypress" />

context('DOM change detection', () => {
  let mutationsHistory
  beforeEach(() => {
    cy.visit('/')

    mutationsHistory = []
    cy.get('#some-id').then(($targetNode) => {
      const observer = new MutationObserver((mutationsList) => mutationsHistory.push(mutationsList))
      observer.observe($targetNode[0], { childList: true })
    })
  })

  it('Should detect the DOM change', () => {
    cy.contains('Mutate after a random delay').click()
    cy.wrap(mutationsHistory)
      .should('have.length.greaterThan', 0)
      .then((mutationsHistory) => {
        cy.log('Now you can do whatever you want with `mutationsHistory`')
        console.log(mutationsHistory)
      })
  })

  it('Should detect the DOM change with cy.waitUntil', () => {
    cy.contains('Mutate after a random delay').click()
    cy.waitUntil(() => (mutationsHistory.length ? mutationsHistory : false)).then(
      (mutationsHistory) => {
        cy.log('Now you can do whatever you want with `mutationsHistory`')
        console.log(mutationsHistory)
      }
    )
  })
})

```

I hope it helps 😉

**Comment by Wulfheart** [comment]
Thank you for this extensive solution.
