### ISSUE TITLE
Cant set timeout option

### ISSUE THREAD

**Issue by SlavikDMI** [NoriSte/cypress-wait-until#139]
cy.waitUntil(() => cy.wrap('445').should('eq', '44'), {
      timeout: 20000,
      interval:2000
    })

Cypress don't wait my timeout, test fails when default time is out.. 
maybe I set timeout option not correctly?

**Comment by NoriSte** [comment]
You cannot use Cypress' assertions inside `cy.waitUntil`. [`cy.wrap` already has retry-ability](https://docs.cypress.io/api/commands/wrap.html#Assertions) and [timeout customization](https://docs.cypress.io/api/commands/wrap.html#Arguments) so go with it without using `cy.waitUntil`!

Your code should look like
- standard version: `cy.wrap('445').should('eq', '44')`
- custom timeout version: `cy.wrap('445', {timeout: 20000}).should('eq', '44')`
- (not necessary) waitUntil version without wrap: `cy.waitUntil(() => '445' === '44', { timeout: 20000, interval:2000 })`
- (not necessary) waitUntil version with wrap: `cy.waitUntil(() => cy.wrap('445').then(myString => myString === '44'), { timeout: 20000, interval:2000 })`

The general advice is: do not use `cy.waitUntil` if you can handle what you need with Cypress built-in functionalities.

Hope it helps, feel free to reopen the issue 😉

**Comment by SlavikDMI** [comment]
Thank you for your answer!
But my example was only example..

This is real case:
When I visit my site, I can see some numbers in [class="tickers__price-value"]
After sometimes (1-10 seconds) numbers will change.
So, I dont want use cy.wait(10), I'd like end test as soon as numbers has been changed.

```
    cy.visit('/')
    cy.get('[class="tickers__price-value"]').invoke('text').then(firstDate => {
      cy.get('[class="tickers__price-value"]').invoke('text').should('eq', firstDate)
    })
  })
```

**Comment by NoriSte** [comment]
I have not tested it but this should be enough with `cy.waitUntil` 😉

```js
cy.visit('/')
cy.get('[class="tickers__price-value"]')
  .invoke('text')
  .waitUntil(
    (firstDate) =>
      cy
        .get('[class="tickers__price-value"]')
        .invoke('text')
        .then((newDate) => newDate !== firstDate),
    {timeout: 20000}
  )
```

Please let me know if it works 😊

**Comment by SlavikDMI** [comment]
Your code works perfect)
Big thanks)

**Comment by NoriSte** [comment]
You're welcome 😊

**Comment by NoriSte** [comment]
@SlavikDMI I was curious and I'd like to solve your problem with Cypress built-ins too... and I found the solution 😊 you can find everything in [this repository](https://github.com/NoriSte/cypress-wait-timeout) and the file you need to checkout is [issue.spec.js](https://github.com/NoriSte/cypress-wait-timeout/blob/master/cypress/integration/issue.spec.js).

Long story short: in the Cypress docs [there is an example of your use case](https://docs.cypress.io/guides/core-concepts/retry-ability.html#Correctly-waiting-for-values) that, applied to your code, looks like the following:

```js
cy.get('[class="tickers__price-value"]')
  .invoke('text')
  .then((firstDate) => {
    cy.get('[class="tickers__price-value"]', { timeout: 20000 }).should(($el) => {
      const newDate = $el.text()
      expect(newDate).to.not.eq(firstDate)
    })
  })
```

- the `timeout` must be set to the `cy.get` call
- the text retrieval must be performed inside the `.should(...)` call

And it works fine 😊

Last but not least: if you have looked for a solution on Google/StackOverflow and you haven't found anything useful... Please help the community doing so

- raise a new question on StackOverflow
- explain well your problem and link to all the resources that seemed helpful but they weren't (and why)
- I'll reply with the solution and you accept it

Doing so:
- the next time you are looking for the same solution you find it directly searching on Google
- you'll help other developers with the same problem
- other useful and alternative solutions could come and we both learn something new

What do you think? 😊
