### ISSUE TITLE
timeout doesn't work

### ISSUE THREAD

**Issue by mesqueeb** [NoriSte/cypress-wait-until#152]
Hi,
I love this extension, because I need the slow interval checking and a long timeout.

However, it seems like it doesn't work at all. It seems like it just checks once, then fails, and never checks again.

My code:
```js
cy.waitUntil(() => cy.get(".e2e-my-lessons-grid > *").should("exist"), { timeout: 120000, interval: 1000 })
```

<img width="505" alt="image" src="https://user-images.githubusercontent.com/3253920/84649813-24e65a80-af42-11ea-9855-1378cde796b6.png">

Any advice much appreciated.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3253920/84649894-45161980-af42-11ea-899e-da5d44f7b280.png">

**Comment by NoriSte** [comment]
Hi @mesqueeb! In order to understand why your use of waitUntil can't work (using a Cypress assertion inside the waitUntil checker function), please take a look at #139 and #35. If they are not enough, feel free to reopen the issue 😉
Best
Stefano

**Comment by NoriSte** [comment]
@mesqueeb last not least: if you only need a different timeout for `cy.get(".e2e-my-lessons-grid > *").should("exist")`... You do not need this plugin! Cypress commands' timeout is customizable, take a look at [`cy.get` options](https://docs.cypress.io/api/commands/get.html#Arguments). 

Then, simply write

`cy.get(".e2e-my-lessons-grid > *", {timeout: 120000}).should("exist")`

**Comment by mesqueeb** [comment]
@NoriSte I understand. thanks for the info.

I did try this however:
```
cy.get(".e2e-my-lessons-grid > *", {timeout: 120000}).should("exist")
```
the problem is that there is no way to set the "interval" and it's literally checking almost every 10ms, really eating up the memory.

That's why I want to use your library to set an interval of around 500ms or so.

How can I use your library to wait until a Dom element exists with a long timeout and an interval of 500ms?

**Comment by NoriSte** [comment]
#75 contains a longer explanation, the solution is

```js
cy.waitUntil(() => Cypress.$(".e2e-my-lessons-grid > *").length, { timeout: 120000, interval: 1000 })
```

**Comment by mesqueeb** [comment]
@NoriSte Again, you're a legend!!
