### ISSUE TITLE
How to wait until a the route URL changes?

### ISSUE THREAD

**Issue by mesqueeb** [NoriSte/cypress-wait-until#153]
I'm not sure why, but this code doesn't work:
```js
const activeLessonTeach = `${Cypress.config("baseUrl")}/#/lesson/teach/`
cy.waitUntil(() => cy.url().should("include", activeLessonTeach), { timeout: 240000, interval: 1000 })
```

<img width="482" alt="image" src="https://user-images.githubusercontent.com/3253920/84845802-66811d80-b088-11ea-81e4-3a638471f9ce.png">

It just fails right away after checking once, instead of checking each 1000 ms for a total of 240 seconds.

Is my syntax wrong?

I read this somewhere:
> You cannot use Cypress' assertions inside cy.waitUntil.

But I still wanna use `waitUntil` with both `cy.get()` and `cy.url()` to make use of its `interval`.

How can I do this?

**Comment by NoriSte** [comment]
Well:

- you can't use `waitUntil` with `cy.get()`. Please, read #75 

- `cy.url()` can be used inside `waitUntil` but you can't use `should('include', /*...*/)` (again, described in #75 )

- so you should replicate the same check `should('include', /*...*/)` does, making something like
```js
const activeLessonTeach = `${Cypress.config("baseUrl")}/#/lesson/teach/`
cy.waitUntil(() => cy.url().then(url => url.includes(activeLessonTeach)), { timeout: 240000, interval: 1000 })
```

This should work, please let me know 😉

**Comment by mesqueeb** [comment]
@NoriSte Thanks so much!!
