### ISSUE TITLE
supporting snapshots with waitUntil would be a game changer

### ISSUE THREAD

**Issue by symon-skelly** [NoriSte/cypress-wait-until#159]
I am using the snapshot plugin linked below to essentially assert large amounts of DOM element state in a single, easy to use command.

https://github.com/cypress-io/snapshot

The problem however is that it is not setup to retry the snapshot state, it checks the DOM once and once only, if the DOM does not match the snapshot, the test will fail, this can happen mostly due to the DOM not being in the correct state because I have failed to find a hook to wait on that is reliable for each test.

I would love to just be able to whack my snapshot command inside a cy.waitUntil() and have it automatically retry the snapshot until it returns true.

It looks like the problem may be because the snapshot plugin throws an error when the snapshot comparison yields a negative result. perhaps I can make an adjustment to this.

**Comment by NoriSte** [comment]
Unfortunately, there is no way to avoid the test failure if something throws an error (read [here](https://stackoverflow.com/questions/56743695/error-handling-using-the-catch-block-in-cypress)) like [the `snapshot` plugin does](https://github.com/cypress-io/snapshot/blob/master/src/index.js#L161) so I cannot be helpful, I'm sorry 😶
