### ISSUE TITLE
cy.waitUntil is not a function

### ISSUE THREAD

**Issue by Eduardo-Carneiro-CM** [NoriSte/cypress-wait-until#161]
Hello,

I keep getting the error **cy.waitUntil is not a function**, anyone had a similar error?
I already have  the line " **import 'cypress-wait-until';** " in the correct file

**Comment by NoriSte** [comment]
I had something similar some time ago but I don't remember how I solved it... Could you share a minimal repository to play with, please?

**Comment by NoriSte** [comment]
@Eduardo-Carneiro-CM did you solve it?

**Comment by markusmurakaru** [comment]
Install this package: https://www.npmjs.com/package/cypress-wait-until

**Comment by rahul-adpushup** [comment]
I have installed this package, but still facing the issue

**Comment by NoriSte** [comment]
Can you share a minimal repo with some reproduction instructions to play with it?

**Comment by Aiosa** [comment]
The same problem here. I don't think minimal example is really needed here, I simply installed the newest version, called ` cy.waitUntil`, and got the same output. Tried to re-install everything (delete modules, clear cache...) and the same outcome. 

I believe it has something to do with version incompatibilities: I use `cypress^10.9.0`. Cypress has quite a migration guide on 10+ version.

**Comment by obgibson** [comment]
Add `import 'cypress-wait-until';` to `commands.ts`

**Comment by NoriSte** [comment]
> Add `import 'cypress-wait-until';` to `commands.ts`

Which Cypress version? Can you share a small repo, pls?

**Comment by obgibson** [comment]
**package.json:**
```
    "cypress": "^13.8.1",
    "cypress-wait-until": "^3.0.1",
```

**commands.ts**
```
    import 'cypress-wait-until';
````
