### ISSUE TITLE
Error of not finding an element even if it shouldn't be there

### ISSUE THREAD

**Issue by htd-tstepien** [NoriSte/cypress-wait-until#167]
I'm slowly losing my mind. Locally, when I fire the CLI or GUI test in Cypress, then it detects the lack of an element and passes this test - such an assumption of the test that after clicking "delete" in the modal, the element is thrown out of the DOM.

BUT the issue is that when I push this to GitHub with CircleCI running the tests. And on CircleCI I get an issue. Is there any point here that I can improve the checking process of no elements in DOM?

Test:
```
it('A user can delete a photo', () => {
      cy.contains('Edit').click();
      cy.uploadFile('jpg-drop');
      cy.get('.photo-container').within(() => {
        cy.contains('Edit').click();
      });
      cy.get('.modal-content').within(() => {
        cy.contains('button', 'Delete').click();
      });
      cy.waitUntil(() =>
        cy.get('.photo-container').then(photoContainer => {
          cy.wrap(photoContainer).should('have.length', 0);
        }),
      );
```

Output:
```
CypressError: Timed out retrying: Expected to find element: '.photo-container', but never found it.
```

**Comment by NoriSte** [comment]
Hi @htd-tstepien 
It's strange that it works locally... because you couldn't use `cy.get('.photo-container')` inside `cy.waitUntil` since `cy.get` asserts by itself. Apart from that, you should replace
```js
cy.waitUntil(() =>
  cy.get('.photo-container').then(photoContainer => {
    cy.wrap(photoContainer).should('have.length', 0);
  }),
)
```
with
```js
cy.waitUntil(() => Cypress.$(".photo-container").length === 0)
```
and it should work. Let me know 😉

**Comment by htd-tstepien** [comment]
> Hi @htd-tstepien
> It's strange that it works locally... because you couldn't use `cy.get('.photo-container')` inside `cy.waitUntil` since `cy.get` asserts by itself. Apart from that, you should replace
> 
> ```js
> cy.waitUntil(() =>
>   cy.get('.photo-container').then(photoContainer => {
>     cy.wrap(photoContainer).should('have.length', 0);
>   }),
> )
> ```
> 
> with
> 
> ```js
> cy.waitUntil(() => Cypress.$(".photo-container").length === 0)
> ```
> 
> and it should work. Let me know 😉

It's working perfectly! @NoriSte
