### ISSUE TITLE
Plugin not working as expected - condition is verified over and over again even it returned true

### ISSUE THREAD

**Issue by borecz** [NoriSte/cypress-wait-until#170]
`cy.window().then(win => {
    cy.waitUntil(() => assert.isDefined(win.dataLayer, 'Data Layer is defined'))
})`

![image](https://user-images.githubusercontent.com/57007154/88337353-e5780e80-cd36-11ea-931a-553b44aece6b.png)

I've been trying to use this plugin for long time but keep getting similar outputs across almost any type of test where I use it.

**Comment by NoriSte** [comment]
`assert.isDefined` returns nothing, take a look at [the source code](https://github.com/chaijs/chai/blob/master/lib/chai/assertion.js#L132-L157). Since it returns nothing, `cy.waitUntil` thinks retries to call the function.
You must transform your code into 
```js
cy.window().then(win => { cy.waitUntil(() => win.dataLayer !== undefined) })
```
Let me know if you need more help 😉
