### ISSUE TITLE
Cypress UI vs command line - not same results

### ISSUE THREAD

**Issue by Kaygi22** [NoriSte/cypress-wait-until#183]
I'm working on a project, where I should test UI components of a streamlit application. 
So I used Cypress. 
The thing is when I created a cypress command where I call waitUntill inside of it
`cy.waitUntil(function() {
      return cy.get('p').contains("Loading ...").should('not.exist')
   })`
It works fine when I test it on Cypress UI
but when I call the same cypress test from terminal using `npx cypress run --spec cypress/integration/createAsset.spec.js`
I get this error

`AssertionError: Timed out retrying: Expected not to find content: 'Loading ...' within the element: [ <p>, 1 more... ] but continuously found it.`

I tried to find out the issue, but until now no luck. 
Does anyone faced the same issue?

**Comment by NoriSte** [comment]
HI @Kaygi22 
More in general, you can't put a Cypress assertion inside the `checkFunction`, quoting the README

> you cannot put assertions inside `checkFunction`. There is no way to avoid a test failure [if an assertion throws an error](https://stackoverflow.com/questions/56743695/error-handling-using-the-catch-block-in-cypress). You must manually check what the assertions would check for you. The most common case is checking that an element exists or not, instead of using `cy.get('#id').should('exist')` you should check that `Cypress.$('#id').length` is greater than `0`. [Here](https://github.com/NoriSte/cypress-wait-until/issues/75#issuecomment-572685623) you can find a deeper explanation

Let me know if you need more details 😊
Stefano
