### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by joetidee** [NoriSte/cypress-wait-until#220]
I am using this package like this:

```
before(() => {
    cy.waitUntil(() => cy.request('GET', baseUrl, { failOnStatusCode: false, timeout: 60000 }),  { timeout: 60000 });
});
```

but Cypress fails with this message:

> The response we received from your web server was:
> 
>   > 504: Gateway Timeout
> 
> This was considered a failure because the status code was not `2xx` or `3xx`.
> 
> If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

It is not waiting until it gets a 200 response.

**Comment by NoriSte** [comment]
First of all: it's not ideal having the same timeout for `cy.request` and `cy.waitUntil`. The latter should have a 4x, 5x, 10x timeout. Anyway, this is not the main problem...

The main error is that `checkFunction`, the first parameter of `cy.waitUntil`, doesn't return a truthy value. The README says

> `checkFunction`: a function that must return a truthy value when the wait is over.

while your function returns `cy.request('GET', baseUrl, { failOnStatusCode: false, timeout: 60000 })`.

Change your code to
```js
before(() => {
  cy.waitUntil(() =>
    cy.request('GET', baseUrl, { failOnStatusCode: false, timeout: 60000 })
      .then(({status}) => status === 200), 
  { timeout: 60000 });
});
```

**Comment by teebu** [comment]
Cypress  8.4.0
cypress-wait-until: 1.7.1

I can't get this to work. 

```
cy.waitUntil(() => {
              cy.request('GET', `https://webhook.site/token/${webhook_uuid}/requests`, { failOnStatusCode: false, timeout: 60000 })
                .then(webhook_reqs_response => true)
            });
```

Even tried adding `.then(r => console.log(r));` to verify it's returning true.
