### ISSUE TITLE
Timeout overriden by defaultCommandTimeout

### ISSUE THREAD

**Issue by GabRog** [NoriSte/cypress-wait-until#232]
In my project I have in cypress.json defaultCommandTimeout set to one minute. 
However, I used wait until in one function, where I wanted to wait for 15 minutes for command to complete. 

Unfortunately, timeout from waitUntil is overriden by defaultCommandTimeout from Cypress. 
Is it expected? If yes, could you give me a tip how to deal with the overriding, to make my 15 minutes more important than defaultCommandTimeout?

**Comment by NoriSte** [comment]
Hi @GabRog. Could you share the code where you're using `waitUntil`, please? I want to double-check that you aren't using code containing Cypress assertions inside the function passed to `waitUntil` (see the [usage notes](https://github.com/NoriSte/cypress-wait-until#usage) for more info).

**Comment by NoriSte** [comment]
@GabRog I close this issue due to inactivity, feel free to re-open it 😊
