### ISSUE TITLE
Wait until SQL query

### ISSUE THREAD

**Issue by vinavega** [NoriSte/cypress-wait-until#237]
Helo people, I'm not being able to make it work on my code, perhaps because inside of the waitUntil chain I'm using a Postgres query from another plugin, I don't know if it should work. I've read docs and tried different ways to use but none worked, I've based in the 5th example of the readme file and reached this code:

```
cy.waitUntil(() => cy.postgreSQL(sql))
                               .then(answer => expect(answer.status).to.be.equal("READY"))
    })
```
The result is that it's not retrying any verification

In case, the plugin I'm using: https://www.npmjs.com/package/cypress-postgresql

**Comment by NoriSte** [comment]
The failing reason is the `expect` assertion. From the README

> you cannot put assertions inside `checkFunction`. There is no way to avoid a test failure [if an assertion throws an error](https://stackoverflow.com/questions/56743695/error-handling-using-the-catch-block-in-cypress). You must manually check what the assertions would check for you. The most common case is checking that an element exists or not, instead of using `cy.get('#id').should('exist')` you should check that `Cypress.$('#id').length` is greater than `0`. [Here](https://github.com/NoriSte/cypress-wait-until/issues/75#issuecomment-572685623) you can find a deeper explanation

Let me know if it helps 😉

**Comment by vinavega** [comment]
oh sorry for not paying the correct attention to it, now it's working with the code this way:
```
.then(answer => answer.status === "READY_FOR_USERS")
```
Thanks a lot for your attention, really appreciated your help

**Comment by NoriSte** [comment]
You're welcome 😊
