### ISSUE TITLE
cy.waitUntil doesnt work in run mode

### ISSUE THREAD

**Issue by Optimus2297** [NoriSte/cypress-wait-until#309]
The cy.waitUntil command is not working in cypress run mode.

**Comment by NoriSte** [comment]
What's the Cypress version? And the plugin version? Could you share a minimal repo with the error, please?

Thanks

Stefano

**Comment by Optimus2297** [comment]
sorry it was an error on my side

**Comment by NoriSte** [comment]
Shit happens, don't worry 😊

**Comment by Optimus2297** [comment]
> Shit happens, don't worry 😊

Thanks for understanding 😊

**Comment by Optimus2297** [comment]
Hii @NoriSte so now I am facing an issue like I am using waituntil for the processing loader to not be visible, but it waits for only 5 seconds and after that it will throw an error. But what I want to achieve is the function should wait until the loader is not visible that  may be irrespective of that 5 seconds time i.e. there should not be a failure, it should wait how much time its required for that loader to not be visible. Is there any config which I can use for this?

**Comment by NoriSte** [comment]
1. Why not using the classic `cy.get('<loader-selector>', {timeout: 10000}).should('not.be.visible', )`?
2. If you want to use `cy.waitUntil` take a look at the [`timeout` option](https://github.com/NoriSte/cypress-wait-until#usage)

**Comment by Optimus2297** [comment]
the issue is there is no understanding of how much time is required, so giving a timeout is not an option

**Comment by NoriSte** [comment]
So if the loader stays out for two days the test should not fail?

**Comment by Optimus2297** [comment]
no i want it to fail but after a significant time like 1 or 2 minitues

**Comment by NoriSte** [comment]
Ok, did you find any technical limitation that prevents you from setting the timeout to 120 seconds? Sorry if I bother you but I'm not sure I 100% understood the root cause of the problem 😉

**Comment by Optimus2297** [comment]
yeah the issue is like we are using cypress for image comparison of ui. But the issue we are facing is like the pages are getting loaded in cypress are taking more time and the time is not consistent then the pages loaded in an actual browser. I are also trying to find the root cause for this, but still no luck.
