### ISSUE TITLE
Document Promise.reject() as anti-pattern

### ISSUE THREAD

**Issue by alycda** [NoriSte/cypress-wait-until#320]
RE: https://github.com/cypress-io/cypress/issues/18557

My example code in the aforementioned issue uses `resolve` and `reject`. My thinking was that retry would continue even on reject but that's not the case. The correct usage is to only use `resolve(true)` and `resolve(false)`, but error handling could be improved both by Cypress and this plugin.

Should there be a `.catch()` block added here? https://github.com/NoriSte/cypress-wait-until/blob/master/src/index.js#L75

**Comment by NoriSte** [comment]
> Should there be a `.catch()` block added here? https://github.com/NoriSte/cypress-wait-until/blob/master/src/index.js#L75

No, because `checkFunction` is passed to the plugin, so if I add a `catch` block results in `result.then(...).catch is not a function`.

I'll add some words in the README,  though.

**Comment by NoriSte** [comment]
I changed my mind. calling `reject()` is the same as throwing an error. It's reasonable, in my opinion, that it bubbles up to Cypress.

Thanks for reporting! Feel free to re-open it if you think it makes sense.
Stefano
