### ISSUE TITLE
Timed out retrying after 4000ms: Expected to find element

### ISSUE THREAD

**Issue by ProxiBlue** [NoriSte/cypress-wait-until#327]
Hello,

I am trying to use this, as such (magento 2 site)

```
cy.waitUntil(() => cy.get('.loader > img').length == 0, {
            interval: 100 // performs the check every 500 ms, default to 200
        });
```

which is to detect if a loader is busy in checkout process, however, once that loader is removed in DOM, I get

```
Timed out retrying after 4000ms: Expected to find element: .loader > img, but never found it.

Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: Checkout Payment Methods
cypress/integration/checkout_methods_spec.js:58:31
  56 |         cy.get('#top-cart-btn-checkout').should('be.visible')
  57 |         cy.get('#top-cart-btn-checkout').click()
> 58 |         cy.waitUntil(() => cy.get('.loader > img').length == 0, {
     |                               ^
  59 |             interval: 100 
  60 |         });
  61 | 
```

Image for visual

![image](https://user-images.githubusercontent.com/4994260/141646801-1736e609-f754-4d9e-816f-165533f22c99.png)

Likely just a syntax/usage issue, but can't figure it out.
Appreciate your effort.

**Comment by NoriSte** [comment]
Hi @ProxiBlue 
You can't put assertions inside the `checkFunction` passed to `cy.waitUntil`. In this case, you didn't insert any assertion directly, but `cy.get` contains assertions itself, take a look at [its docs](https://docs.cypress.io/api/commands/get#Assertions). You should replace it as follows
```diff
-cy.get('.loader > img').length == 0
+Cypress.$('.loader > img').length == 0
```

let me know if it works.\
Stefano

**Comment by ProxiBlue** [comment]
It works, thanks a million.
