### ISSUE TITLE
Global timeout

### ISSUE THREAD

**Issue by GustavoRochaSantos** [NoriSte/cypress-wait-until#336]
Can i define a timeout value for waitUntil without passing by params?

**Comment by NoriSte** [comment]
Not at the moment, I'm sorry 😶

**Comment by GustavoRochaSantos** [comment]
i understand... i tried to overwrite the waitUntil to set the timeout , but doesn't worked. Is it not possible too?

**Comment by NoriSte** [comment]
#337 is related to the same topic
