### ISSUE TITLE
Overwrite WaitUntil command

### ISSUE THREAD

**Issue by GustavoRochaSantos** [NoriSte/cypress-wait-until#337]
Hello! Is possible to overwrite the waitUntil command with Cypress.overwrite('waitUntil',.... to set up a global timeout? How can i do this?

**Comment by NoriSte** [comment]
I guess something like this? (I haven't tested it out)

```js
Cypress.Commands.overwrite('waitUntil', (originalFn, checkFunction, originalOptions = {}) => {
  return originalFn(subject, checkFunction, {
    ...originalOptions,
    timeout: 10000, // <-- your global timeout
  })
})
```

**Comment by NoriSte** [comment]
@GustavoRochaSantos did you get it work? If yes, how? Can I close this issue?

**Comment by GustavoRochaSantos** [comment]
Hi, didn't work, so I removed of my project. You can close
