### ISSUE TITLE
How to write test code about progess bar by waituntil

### ISSUE THREAD

**Issue by trackuitest** [NoriSte/cypress-wait-until#341]
hi,
I've seen the usage of cypress-wait-until, but I still don't know how to write a scenario case about progess bar 
by this method？
`cy.waitUntil(() => {
            return Cypress.$(XXXXXXXX).length
        })`
The scenario  is similar to this picture
What I want to test is that 
when backend api change some data and send message to frontend , the frontend monitors the changes and updates the UI,
![image](https://user-images.githubusercontent.com/89202885/149122433-6db701b1-a580-430a-916f-620525610b79.png)

Another question is whether cypress-wait-until can only end the wait by judging true or false?

**Comment by NoriSte** [comment]
Welcome 👋

> when backend api change some data and send message to frontend , the frontend monitors the changes and updates the UI,

I guess the backend send messages through a socket connection? Anyway, why a simpler, Cypress-based, approach like the following doesn't work for you?
```js
cy.contains('[TEXT OF THE STEP 1]').should('be.visible')
cy.contains('[TEXT OF THE STEP 2]').should('be.visible')
cy.contains('[TEXT OF THE STEP 3]').should('be.visible')
// ...
```

> Another question is whether cypress-wait-until can only end the wait by judging true or false?

It ends the wait for [every truthy value](https://github.com/NoriSte/cypress-wait-until/blob/master/src/index.js#L56), not only booleans.

**Comment by trackuitest** [comment]
thank you

**Comment by NoriSte** [comment]
You're welcome 😊
