### ISSUE TITLE
Wait for DOM change in order to assert completion of a job

### ISSUE THREAD

**Issue by akus062381** [NoriSte/cypress-wait-until#350]
Our platform has a job running feature. The different displayed statuses include: Running, Successful, Failed, Canceled, and Error. 

Jobs run via playbooks, and runtime length can vary greatly. We often write tests that require Cypress to wait until a job is finished running in order to assert something.

I want to use cy.waitUntil to wait for 'Running' to no longer be displayed in a certain element in order to proceed with the test commands. I have tried many different things. This is my most recent attempt (so far none of my different ways have worked):

```javascript
const jobStatusValue = 'Successful'
const checkFunction = () =>
  cy.findByCustomId('job-status-value').then((jobStatus) => jobStatus.text === jobStatusValue)

cy.waitUntil(checkFunction, { timeout: 60000 })

cy.findByCustomId('job-status-value')
  .invoke('text')
  .should((text) => {
    expect(text).to.contain('Successful')
  })
```

Can you please help me figure out a good way to do this? I would so appreciate it!

**Comment by NoriSte** [comment]
Uhm, you don't need `cy.waitUntil` for what you described...\
I don't know exactly what your `findByCustomId` does, but staying with pure Cypress, why a simple
```js
cy.get('[data-testid="job-status-value"]').contains('About', { timeout: 60000 })
```
doesn't work?

**Comment by akus062381** [comment]
@NoriSte I was way overthinking this I suppose! this works, and thank you.

**Comment by NoriSte** [comment]
You're welcome! 😊

#341 was similar, I should probably add one more section in the main readme.\
The point is: Cypress already allows waiting for almost anything, for the rare occasion where it doesn't, `cy.waitUntil` comes in help.
