### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [NoriSte/cypress-wait-until#371]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by liambutler** [comment]
@admah It would be great if the functionality that `cypress-wait-until` provides was made part of the official Cypress offering. Similar to the great work your team did on [cy.selectFile()](https://docs.cypress.io/api/commands/selectfile)

**Comment by NoriSte** [comment]
> Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10.
> 
> For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

I confirm the plugin is compatible since I used it at Hasura and we had no issues with Cypress 10 😊

**Comment by NoriSte** [comment]
> @admah It would be great if the functionality that `cypress-wait-until` provides was made part of the official Cypress offering. Similar to the great work your team did on [cy.selectFile()](https://docs.cypress.io/api/commands/selectfile)

I'd suggest you raise an issue on the Cypress repo 😊❤️
