### ISSUE TITLE
not waiting specified wait time between checks

### ISSUE THREAD

**Issue by peetjvv** [NoriSte/cypress-wait-until#39]
I've been trying to use your package in my Cypress project, but unfortunately I can't get it to wait for the specified interval. From what I can tell it retries the specified checkFunction immediately timeout/interval times and does not wait at all between tries.

Here is my code:
```javascript
cy.getStore().then(store =>
  cy.waitUntil(
    () => {
      const things = store.getState().things;
      console.log(things, !!Object.keys(things).length);
      return !!Object.keys(things).length;
    },
    {
      errorMsg: 'wait until things loaded error',
      timeout: 10000,
      interval: 1000,
    }
  )
);
```

I have also tested this without specifying any custom options, but that didn't work either.

Is there anything that I am maybe doing wrong in my implementation? Or is this an issue on your side? Also, looking at your tests it doesn't seem like you have a test that will test whether or not there were sufficient time waited between tries.

Package versions:
cypress 3.4.1
cypress-wait-until 1.3.0

**Comment by NoriSte** [comment]
Hi @peetjvv 
Try inverting the `getStore`/`waitUntil` calls
```javascript
cy.waitUntil(() => {
  cy.getStore().then(store => {
    const things = store.getState().things;
    console.log(things, !!Object.keys(things).length);
    return !!Object.keys(things).length;
  })
});
```
or, super shortened
```javascript
cy.waitUntil(() => cy.getStore().then(store => !!Object.keys(store.getState().things).length));
```

and let me know if it works!
Then, we can think about the missing test (you're right about it).

Waiting for your feedback
Stefano

**Comment by peetjvv** [comment]
That workaround worked, thank you. There is a bit of overhead in my getStore command that I was hoping to avoid though. I wonder if the feature request I made in #40 wouldn't resolve this issue. I'll look into it again once that feature is implemented.

**Comment by NoriSte** [comment]
@peetjvv you were right, I've just fixed and released it (1.4.0), let me know if it works for you

**Comment by peetjvv** [comment]
all good now, thanks!

**Comment by NoriSte** [comment]
You're welcome 😊sorry for the bug!
