### ISSUE TITLE
Cypress configuration error

### ISSUE THREAD

**Issue by AlexQuei** [NoriSte/cypress-wait-until#398]
Hello everyone,

I am already a Cypress-wait-until user but on a Cypress 10- version, I have just implemented it on another Cypress 10.2 solution.

I get the following error: Cypress configuration error
Your configFile is invalid: C:\Users\...\cypress.config.js
![Cypress_2022-08-04_16-10-40-026](https://user-images.githubusercontent.com/108526193/182868332-77a17856-e8cf-4a4e-946f-de14f1fb2bfd.png)

TS config file is correctly included cypress-wait-until and the package is correctly imported in cypress.config.js.

I don't know what is wrong. Can you please help me ? Thank you in advance.

best regards.

**Comment by NoriSte** [comment]
Uhm... it's strange... could you please create a bare minimal repo where I can play with it, please?

**Comment by AlexQuei** [comment]
This is a mistake...
This morning I realized that I had the import in cypress.config.js instead of cypress/support/e2e.js.

I confused merging the support/e2e.js file with cypress.config.js and merging the plugin/index.js file with cypress.config.js. So I thought I should put it directly in the config file.

My bad.

Your plugin works fine with 10.2.
I let you close this ticket.

Have a great day and great thanks for your work.

Best regards.

**Comment by NoriSte** [comment]
Thank you so much, and don not worry, shit happens 😊

Have a great day and weekend 🤗
Stefano
