### ISSUE TITLE
feature request: passing subject from previous chained command to waitUntil

### ISSUE THREAD

**Issue by peetjvv** [NoriSte/cypress-wait-until#40]
It would be nice if I can pass the subject from the previous command in the chain of cypress commands into my checkfunction without having to use .then like this:

```javascript
cy.getStore().then(store =>
  cy.waitUntil(
    () => {
      const things = store.getState().things;
      console.log(things, !!Object.keys(things).length);
      return !!Object.keys(things).length;
    }
  )
);
```

It would be ideal if I can do something like this:

```javascript
cy.getStore().waitUntil(store => !!Object.keys(store.getState().things).length));
```

**Comment by NoriSte** [comment]
Thank you @peetjvv for the suggestion! Definitely we must add it! I'm pretty busy at the moment so I won't add it in the next days, would you like to submit a PR with that?
Thank you
Stefano

**Comment by peetjvv** [comment]
I was planning on giving it a go and submitting a PR myself, but I'm also quite busy atm unfortunately

**Comment by NoriSte** [comment]
@peetjvv I've just implemented and released it (1.4.0), let me know if it works for you and if you need something more 😉

**Comment by peetjvv** [comment]
@NoriSte v1.4.0 is working perfectly. It even works with my ideal solution that I wanted to use originally:

```javascript
cy.getStore().waitUntil(store => !!Object.keys(store.getState().things).length));
```

Thanks for your help, speedy updates and nice new tests!

**Comment by NoriSte** [comment]
You're welcome ❤️

**Comment by peetjvv** [comment]
unfortunately it only seems works for me with `cypress open` and not `cypress run`. If I have a sec I'll investigate further and let you know.

**Comment by NoriSte** [comment]
Ok, let me know if we can do something for you (or how you solved it). I have just read the Travis log and there is nothing wrong about `cypress run` with the pipeline.
