### ISSUE TITLE
Using cy.reload() - Failed because you are mixing up async and sync code.

### ISSUE THREAD

**Issue by leo-coco** [NoriSte/cypress-wait-until#443]
I try to use `cypress-wait-until` for a simple case.

1. Visit a page
2. Check if an element is here (the element will be available a couple of second after page load)
3. If not, reload the page until this element is found.
4. Once found, assert the element exists

**Working code (cypress-wait-until not used)**
```
before(() => {
    cy.visit('http://localhost:8080/en/registration');
});

describe('Foo', () => {
  it('should check that registration button is displayed', () => {
    const selector = 'button[data-test=startRegistration-individual-button]';
    cy.get(selector).should('exist');
  });
});
```

**Not working, timed out retrying**
```
before(() => {
    cy.visit('http://localhost:8080/en/registration');
});

describe('Foo', () => {
  it('should check that registration button is displayed', () => {
    const options = { timeout: 8000, interval: 4000 };
    const selector = 'button[data-test=startRegistration-individual-button]';
    cy.waitUntil(() => cy.reload().then(() => Cypress.$(selector).length), options);
    cy.get(selector).should('exist');
  });
});

```

**Not working, see error below**
```
before(() => {
    cy.visit('http://localhost:8080/en/registration');
});

describe('Foo', () => {
  it('should check that registration button is displayed', () => {
    const options = { timeout: 8000, interval: 4000 };
    const selector = 'button[data-test=startRegistration-individual-button]';
    cy.waitUntil(() => {
        cy.reload();
        return Cypress.$(selector).length;
      }, options);

    cy.get(selector).should('exist');
});

```
<img width="744" alt="image" src="https://user-images.githubusercontent.com/17890087/216737184-58b747f4-8c50-409a-8bd9-098aa6b2af67.png">

For the two versions not working as soon as I remove `cy.reload()`, it starts to work.

**Comment by NoriSte** [comment]
Please checkout this comment
https://github.com/NoriSte/cypress-wait-until/issues/355#issuecomment-1047684589
at a first glance (I'm from mobile) it looks you need to do the same 😊

**Comment by leo-coco** [comment]
Actually, my second example was the good one but I had to add wait time. You can close this bug, thanks for your time

` cy.waitUntil(() => cy.reload().wait(2500).then(() => Cypress.$(selector).length), options);`

**Comment by NoriSte** [comment]
You're welcome 😊

**Comment by leo-coco** [comment]
@NoriSte, would you actually have a suggestion to make this scenario work without the need to have a fixed wait time of 2500ms?

**Comment by NoriSte** [comment]
Maybe a `cy.waitUntil` inside the main one but ATM it should not work...
