### ISSUE TITLE
Not working on the latest cypress version

### ISSUE THREAD

**Issue by rakeshnambiar** [NoriSte/cypress-wait-until#450]
Not working on the latest cypress version. Please could you update how this has to be configured in the latest Cypress config file? The existing configuration mentioned in the documentation is almost obsolete. Appreciate also it if you could explain and include the sample about how it will wait for an element to be visible. Moreover, will it take the maximum wait time from the `defaultCommandTimeout` parameter?

**Comment by NoriSte** [comment]
Hey!! 👋👋👋

> Not working on the latest cypress version.

Could you point me to a simple GH repo that shows it's not working, please? I just
1. Created a new project `$ npm create vite@latest`
2. Installed Cypress (the latest one, 12.8.0)
3. Opened it
4. Configured `cypress-wait-until` as reported in the README
5. Used it

And everything works... 🤔


>  Please could you update how this has to be configured in the latest Cypress config file? The existing configuration mentioned in the documentation is almost obsolete.

Could you point me to the obsolete parts, please? By doing the steps I shared everything seems fine to me 🤔


> Appreciate also it if you could explain and include the sample about how it will wait for an element to be visible

In the README you can find this

> you cannot put assertions inside checkFunction. There is no way to avoid a test failure [if an assertion throws an error](https://stackoverflow.com/questions/56743695/error-handling-using-the-catch-block-in-cypress). You must manually check what the assertions would check for you. The most common case is checking that an element exists or not, instead of using cy.get('#id').should('exist') you should check that Cypress.$('#id').length is greater than 0. https://github.com/NoriSte/cypress-wait-until/issues/75#issuecomment-572685623 you can find a deeper explanation

do you think it's not enough?


> Moreover, will it take the maximum wait time from the defaultCommandTimeout parameter?

Not at the moment

**Comment by rakeshnambiar** [comment]
@NoriSte Do you have a sample project for me to refer with the latest configurations?

**Comment by NoriSte** [comment]
Here it is https://github.com/NoriSte/cypress-wait-until-issue-450

**Comment by rakeshnambiar** [comment]
@NoriSte thanks a lot. I am using entirely a different setup. Seems it is now configured correctly. However, please have a look https://github.com/rakeshnambiar/wait-until

**Comment by NoriSte** [comment]
> However, please have a look https://github.com/rakeshnambiar/wait-until

What should I look at there?

Meanwhile, I close this issue if you do not mind 😊
