### ISSUE TITLE
Timeout can take longer than defined

### ISSUE THREAD

**Issue by liambutler** [NoriSte/cypress-wait-until#464]
Love this plugin, has been so useful! However, there's something that was puzzling me for ages.

I couldn't understand why my `waitUntil()` function was set to time out after 60000ms, but was taking longer than two minutes to fail.

It's because [this line](https://github.com/NoriSte/cypress-wait-until/blob/master/src/index.js#L50) doesn't factor in the time that it takes to perform an action. 

So if I have the following config:

```js
      {
        timeout: 60000,
        interval: 1000,
        errorMsg: `Could not find ${id} in ${documentType} after 60s`,
      }
```

and I'm looping an API call that takes 1s to resolve, it'll perform that call 60 times, with a 1 second interval between. Hence a one minute timeout takes two minutes.

**Comment by NoriSte** [comment]
> Hey @NoriSte, I believe that I have come up with a fix for this. Would it be possible for me to be granted access so I can raise a PR?

Thank you!! Dumb question: doesn't GitHub allow you to follow the standard contribution process? That is
1. You fork the repo
2. You create a new branch in the fork
3. You open a PR in this repo by comparing your fork's branch to this repo's master branch

?

**Comment by liambutler** [comment]
Figured it out! PR here: https://github.com/NoriSte/cypress-wait-until/pull/465

I've tested against my own project using Cypress, but I wasn't able to get results from running `npm test`. Cypress wasn't happy because the repo has the old `cypress.json` rather than the `cypress.config.js` favoured by v10 and above
