### ISSUE TITLE
wrong casing on reference types causes typscript build issues

### ISSUE THREAD

**Issue by piccit** [NoriSte/cypress-wait-until#481]
I have an internal helper library that uses cypress-wait-until written in typescript. When trying to update to typescript 5.5 it fails to build due to `Cannot find type definition file for 'Cypress'` / "file name differs only in casing" referring to `Cypress` vs `cypress`. The capital C `Cypress` is coming from cypress-wait-until's [index.d.ts ](https://github.com/NoriSte/cypress-wait-until/blob/master/index.d.ts#L1) and [plugin.spec.ts](https://github.com/NoriSte/cypress-wait-until/blob/master/cypress/types/plugin.spec.ts#L1). The actual cypress node module is all lowercase, so I believe these 2 references should be `/// <reference types="cypress" />` instead of using a capital C

**Comment by NoriSte** [comment]
@all-contributors please add @piccit for bug

**Comment by NoriSte** [comment]
Thank you for reporting it!! Let me know if the just-published `3.0.2` fixes it :)

**Comment by piccit** [comment]
> Thank you for reporting it!! Let me know if the just-published `3.0.2` fixes it :)

Works like a charm, thanks!
