### ISSUE TITLE
Run function option

### ISSUE THREAD

**Issue by jackwarm** [NoriSte/cypress-wait-until#50]
I needed a way to press a button on the page before I recheck the condition.

I added the following to your code to include a command option that is executed before a retry. 

  options = options || {}

  const TIMEOUT_INTERVAL = options.interval || 200
  const TIMEOUT = options.timeout || 5000
  const ERROR_MSG = options.errorMsg || 'Timed out retrying'
  const COMMAND = options.command || {}
  let retries = Math.floor(TIMEOUT / TIMEOUT_INTERVAL)

  const check = result => {
    if (result) {
      return result
    }
    if (retries < 1) {
      throw new Error(ERROR_MSG)
    }
    cy.wait(TIMEOUT_INTERVAL).then(() => {
      retries--
      COMMAND();
      return resolveValue()
    })
  }

**Comment by NoriSte** [comment]
Something like this could work for you without any change to the library?
```js
cy.waitUntil(() =>
  cy
    .get("button")
    .click()
    .then(() => /* YOUR_CHECK */)
);
```

**Comment by NoriSte** [comment]
@jackwarm I close the issue due to inactivity, feel free to reopen it 😊
