### ISSUE TITLE
global timeout and interval settings

### ISSUE THREAD

**Issue by SteveSchreiner** [NoriSte/cypress-wait-until#62]
Hi,

Awesome library! Is there a way to override the timeout and interval settings for all waitUntil calls? Instead of having to pass it into each waitUntil?

Thanks!

**Comment by NoriSte** [comment]
Thank you @SteveSchreiner 
Not at the moment, feel free to submit a PR for that 🤗

**Comment by NoriSte** [comment]
@SteveSchreiner I close this PR due to inactivity, feel free to re-open it or submit a PR 😊
Best
Stefano
